### ISSUE TITLE
Doesn't work with axios?

### ISSUE THREAD

**Issue by jkotchoff** [meeshkan/unmock-react-native-example#6]
Thank you for open sourcing unmock, this is a terrific tool.

One issue for me is that this example app works as expected with `fetch`, however surprisingly, when content is retrieved using `axios` in react native, unmock fails to mock http calls

ie.
https://github.com/jkotchoff/unmock-react-native-example/commit/58caf82536471afdc74840ad96a5c92289405975

incorrectly results in an actual cat fact:
<img width="350" alt="ios screenshot of the above fork" src="https://user-images.githubusercontent.com/58198/82844654-9ffcb800-9f24-11ea-9317-e95123da6add.png">

when it should instead be displaying some lorem ipsum.

This is unusual, because unmock doesn't seem to do this with axios in a vanilla node project, ie. without react native.

When I was testing it on some of my own urls (possibly using _.post_ instead of _.get_), I think I saw an error like: `Failed fetching fact: Can't find variable: ProgressEvent`.

Any idea what's going on here?

**Comment by mikesol** [comment]
Hi! Thanks for this. `axios` uses `XMLHttpRequest` under the hood, so there may be a bug in the implementation of `XMLHttpRequest` used in `unmock-browser`. I will have a look and let you know what I turn up!

**Comment by mikesol** [comment]
Hi @jkotchoff , I had a chance to look into the issue and I have a couple questions for you.

- Could you please try your example using the most recent version of unmock (0.3.17)? If that works, let me know. I just tested unmock+axios using unmock 0.3.17 on https://snack.expo.io/@mikesol/unmock and it works for that particular example.
- If that doesn't work, could you please migrate this issue to [unmock-js](https://github.com/unmock/unmock-js).

**Comment by jkotchoff** [comment]
Thanks for following up Mike. I was actually testing with `0.3.17` when the behaviour failed to work. This is [now documented](https://github.com/jkotchoff/unmock-react-native-example/commit/1492d3f9a53ca44a944f5f421cdd9efed77e6a5e) in that fork. I'll move the issue over.
